apiVersion: v1
kind: ConfigMap
metadata:
  name: healthcare-config
  namespace: healthcare
  labels:
    app.kubernetes.io/part-of: smart-healthcare
    app.kubernetes.io/component: config

data:
  NODE_ENV: "production"

  API_GATEWAY_PORT: "3000"
  USER_SERVICE_PORT: "3001"
  DOCTOR_SERVICE_PORT: "3002"
  APPOINTMENT_SERVICE_PORT: "3003"
  TELEMEDICINE_SERVICE_PORT: "3004"
  PAYMENT_SERVICE_PORT: "3005"
  NOTIFICATION_SERVICE_PORT: "3006"

  USER_SERVICE_URL: "http://user-service:3001"
  DOCTOR_SERVICE_URL: "http://doctor-service:3002"
  APPOINTMENT_SERVICE_URL: "http://appointment-service:3003"
  TELEMEDICINE_SERVICE_URL: "http://telemedicine-service:3004"
  PAYMENT_SERVICE_URL: "http://payment-service:3005"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3006/api/notifications/internal"
  API_GATEWAY_URL: "http://api-gateway:3000"

  OPENAI_MODEL: "gpt-4o-mini"
  JITSI_DOMAIN: "meet.jit.si"
  JITSI_ROOM_PREFIX: "appointment"

  PAYHERE_SANDBOX: "true"

  NODEMAILER_HOST: "smtp.gmail.com"
  NODEMAILER_PORT: "587"
  NODEMAILER_FROM: "Smart Healthcare <your-email@example.com>"
